### ISSUE TITLE
PermissionError on Save Results

### ISSUE THREAD

**Issue by JordanRees** [hsoft/dupeguru#266]
```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 3.9.0
Mac OS X Version: Version 10.9.5 (Build 13F34)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/core/results.py", line 371, in save_to_xml
  File "build/dupeGuru.app/Contents/Resources/py/core/results.py", line 367, in do_write
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/util.py", line 386, in __enter__
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/util.py", line 342, in open_if_filename
PermissionError: [Errno 13] Permission denied: '/Duplicates20141014.dupeguru'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/inter/app.py", line 86, in saveResultsAs_
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 708, in save_as
  File "build/dupeGuru.app/Contents/Resources/py/core/results.py", line 380, in save_to_xml
  File "build/dupeGuru.app/Contents/Resources/py/core/results.py", line 367, in do_write
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/util.py", line 386, in __enter__
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/util.py", line 342, in open_if_filename
PermissionError: [Errno 13] Permission denied: '/Duplicates20141014.dupeguru'

Relevant Console logs:

There was an error trying to detect the UTI of /dev
There was an error trying to detect the UTI of /dev
There was an error trying to detect the UTI of /dev
```

**Comment by hsoft** [comment]
I don't know why this ticket is still opened. The fix is already there and included in the latest releases.
