### ISSUE TITLE
Defect - multi-add / remove re-prioritize "Folder"

### ISSUE THREAD

**Issue by shoffmeister** [hsoft/dupeguru#283]
It is possible to add the same "Folder" twice in the "Re-Prioritize duplicates" dialog. Removing one of the duplicates then leads to an error (see end of this report).

Steps:
- run software on a nested directory structure which yields a number of source folders
- Actions -> Re-Prioritize Results ...
//dialog comes up
- switch to "Folder" item in combobox
//folders are listed
- click once on first folder entry
- click on "->" arrow in middle

//exp: folder disappears from the left list (and is added to the right list)
//act: folder remains on the left list (and is added to the right list)

- click (again) on "->" arrow in middle
//folder is added again to the right list

- click on the last entry in the right list
- click on "<-" arrow in middle

//exp: removes duplicate(d) entry
//act: runtime exception (see below)

It is quite conceivable that is could also be due to an unstable algorithm used when deleting from the list on the right side (typical pattern). Such an algorithm would look at the count of items in a list (which is unstable in a delete situation) as opposed to iterating over the list (which is robust even in the presence of deletes).

This is happening on Windows 8.1
--------------
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\qtlib\selectable_list.py", line 26, in data
  File "C:\src\dupeguru\hscommon\gui\selectable_list.py", line 115, in __getitem__
IndexError: list index out of range

**Comment by hsoft** [comment]
Thanks for this thorough report. I'll try to reproduce it as soon as I have the time.

**Comment by fujifilm99** [comment]
This also happened on Linux Mint Cinnamon 17.1
I'm unsure of the steps I followed to get it, but it appears to be the same line numbers. If it Is not the same error, I can put it in as a new one if it happens again.
Application Name: dupeGuru Picture Edition
Version: 2.10.1

Traceback (most recent call last):
  File "/usr/share/dupeguru_pe/qtlib/selectable_list.py", line 26, in data
    return self.model[index.row()]
  File "/usr/share/dupeguru_pe/hscommon/gui/selectable_list.py", line 115, in __getitem__
    return self._items.__getitem__(key)
IndexError: list index out of range
