### ISSUE TITLE
New Option to only treat files as duplicates if contained in different base folders

### ISSUE THREAD

**Issue by mmoole** [hsoft/dupeguru#296]
Dear dupeguru team,

this feature request is a new option (maybe a checkbox in the preferences) that would tell dupeguru to report only on duplicates when the concering files are distributed in different base folders (with base folders I mean those folder you add when choosing what to scan).

This would mean that if we got those files:
```
- base folder 1
 - file-a
 - subfolder 1
  - file-a
  - file-b
  - file-c
- base folder2
 - file-b
 - file-c
```
then only the file-b and file-c would be reported as duplicates because file-a only exists in base folder 1.

That would be extremely useful! Then I would be able to compare against an old CD or DVD and find out precisely about what to keep and what to delete without being blown away by the huge amount of duplicates I have just on my harddrive.

**Comment by hsoft** [comment]
Do you know about the ["Reference" folder type](http://www.hardcoded.net/dupeguru/help/en/folders.html#folder-states) in the Folder Selection dialog? It sounds like it does what you want.

**Comment by mmoole** [comment]
Yes, I tried with the reference folder, but ran into a problem:
* eventually only file-b and file-c are displayed if I set folder 1 to be reference.
But then I cannot delete those files in base folder 1 because they are in a reference folder.
I tried to invert selection or delete selected from list, but it didnt work out. 

Otherwise (folder 2 is reference) it still keeps listing all and every duplicates. For this it would be useful to only obtain a report of those files that are in both 'base folders' and being able to delete those.

**Comment by hsoft** [comment]
I think I misunderstood the problem at first, now I think I get it. If you have many folders under `base folder 1`, your experience will indeed be cumbersome.

Whenever possible, I try to avoid adding new preference because users tend to now know what they're for. I'd have two alternatives (both impossible for now, they'd have to be implemented) to adding the option you suggested, I'd appreciate if you could confirm that they'd work for you.

== Alternative 1: Add many folders at once

The core problem is that you don't actually scan `base folder 1` right? What if, when clicking the `+` button in the folder selection dialog, you shift-selected all subfolders under `base folder 1` and added them to the folder selection? Wouldn't that solve your problem?

== Alternative 2: Mass folder state assignment

What if after having added `base folder 1`, you set its state to `Ignored` and then un-ignore all subfolders? Right now, it's tiresome to do because you can only do it to one folder at once, but with a little work, it would be rather easy to allow mass assignment of folder states. I think that would also solve your problem.

What do you think?

**Comment by mmoole** [comment]
That's good philosophy about adding preferences - otherwise the program would be very cluttered by now I think :+1:

I tried to do the alternatives, but didn't come to the expected result of only getting reported file-c and file-d. But in this case, some of the files are indeed contained in the base folders.
Initially I created this for testing:
![screenshot1](http://abload.de/img/screen1a6u6w.png)

Maybe I did something wrong?
So by set theory I would like to get a list of duplicates where each match is at least once contained in the base folders and at the same time at least once in the 'master' base folder that would be the dvd for example. 
So the result of that type of scan of the structure in the image would only report file-c and file-d as duplicates. Even file-e would not be reported because it's only contained folder 2.

**Comment by hsoft** [comment]
Now I'm confused. Your rules don't seem to be the same as in your first message. By your screenshot, why wouldn't `file-a.pdf` be included in the results? It's in both "unterordner" and "dupes folder 1".

**Comment by mmoole** [comment]
file-a is not contained in the path of base-folder 2, that's why it would be excluded. 

I went out searching the net and indeed there are not many programs offering that.
But I found name for it: non-inclusive mode - when turned on, files in this path will not be compared against other files in the same path.

But since the 'reference' type already makes it possible to obtain the good list of results, I don't know how to approach this. 
Maybe an action like 'invert reference and normal folder results' would already lead to being able to select file-b and file-c and then delete them?

**Comment by hsoft** [comment]
`file-d` is not in base-folder 2 either. Why should it be included in the results?

**Comment by mmoole** [comment]
exactly, so `file-d` it should not be in the results. I think I made a typo there, sorry!
For this example, only `file-b` and `file-c` should be in the list of results. :-)

**Comment by hsoft** [comment]
`file-b`?! You're losing me. It's not in any of the two subfolders. I don't understand what you're trying to get at.

**Comment by mmoole** [comment]
`file-b` is in the path of `base folder 1` and at the same time the path of `base folder 2` and they are the ones I added to dupeguru for comparing.

the only thing is in the image they are called differently.

**Comment by mmoole** [comment]
Maybe another way to express this would be:
use `folder-1` as 'search criteria'

**Comment by hsoft** [comment]
I'm really confused, You'll need to explain better.

I can arrive to `b` and `c` in the results by doing this:

`folder-1`: normal
`unterordner`: excluded
`folder-2`: reference
`unterordner-2`: reference

But I really don't understand what you're trying to do. All of this makes no sense to me.

**Comment by mmoole** [comment]
let's try to illustrate it with this use case:

I have a DVD that contains lots of files that I have archived some time ago.
On the other hand, my computers hdd is filled with a lot more files. 
Some hundred files are both on the DVD and my hdd because that is what happened over time. 
Space is running low, so I want to clean up.

So let's delete those files from the hdd that are already archived on the DVD. But how to find out those files that reside both on the DVD and the hdd and are duplicates? Only those files can be safely deleted since they are already archived on DVD. 
That's what one could scan for with dupeguru.

I hope this makes sense now?

**Comment by hsoft** [comment]
You can do that by setting the DVD as Reference in the folder selection dialog and your HDD as Normal. Then, only files in your HDD that are also in your DVD will be in the results.

**Comment by mmoole** [comment]
Well, it seems I can not arrive to get to this result.

I renamed the folders for the example and tried with these settings:
![screen4](http://abload.de/img/screen44mb64.png)

But then also the duplicates that are only in the hdd folder are on the list. If there would be an easy way to filter them out that would be great, too :)

**Comment by tkoyn** [comment]
I downloaded the code because I am interested in this issue too. I coded (but did not setup build enviroment or test) the following that I think will do what the OP asked for, except there is no preference to turn it on.

In scanner.py, get_dupe_groups function....

1) Right after we set is_ref to False for files that do not have the is_ref attribute, add

        # Koyn : Determine if there are any reference files.
        any_reference_files = any(f.is_ref for f in files)    

2) Right after we remove matches where both files are reference, add the following

        # If there are any reference files we need to exclude matches where both files are not reference.
        if any_reference_files:
            matches = [m for m in matches if not (not m.first.is_ref and not m.second.is_ref)]

My intent is that if a user has any files setup as Reference in their search, that we only look for duplicates among the non-reference materials that are duplicate to items in the reference materials. This will eliminate showing duplicate pairs where both files are not Reference. Furthermore, if the user does not choose anything to be Reference in the search, then I do not exclude any pairs of files.

(Note: While I am a software developer, I am completely new to the Python language and have not setup the build environment yet, so the above is merely to express my idea and may contain syntax errors.)

**Comment by hsoft** [comment]
@tkoyn is this what this request really is about? If yes, then I'm glad because it clarifies things a lot because I understand what you're trying to achieve with this code. But I can't know for sure that we're actually solving the same problem.

If we are, then implementation is easy. The hardest part will be to come up with an option name *that is not confusing*. I really want to avoid adding obscure options that no one ever use because they don't understand it (even when they *would* need it).

**Comment by hsoft** [comment]
... or maybe that instead of an option, it could be a folder State (along with Normal, Reference, Excluded). But then again, what should be call it?

**Comment by tkoyn** [comment]
On Jun 23, 2015, at 9:07 AM, Virgil Dupras <notifications@github.com> wrote:
> @tkoyn is this what this request really is about? If yes, then I'm glad because it clarifies things a lot because I understand what you're trying to achieve with this code. But I can't know for sure that we're actually solving the same problem.
> 
I think my proposed change would satisfy the original poster's need, based on reading his third post, when he is considering use of Reference in his application. Even if I did misunderstand some detail of the request, my proposed change would address a need I have and is something I would like to have.

> If we are, then implementation is easy. The hardest part will be to come up with an option name that is not confusing. I really want to avoid adding obscure options that no one ever use because they don't understand it (even when they would need it).
> 

I am not sure if there needs to be a user option at all. The way I drafted the proposed code change, the program will not match "Normal" files to each other if anything has been denoted "Reference". And if there are no "Reference" folder(s), 'Normal' files will still be matched to each other.

However if you wish to implement with a user option, here are some checkbox title ideas:

"Compare Normal only to Reference"
"Match Normal only to Reference"

If the checkbox is created, and the user checks it, and then runs a job with no 'Reference', then the program should NOT switch to matching 'Normal' files as I originally proposed, but should instead display a message "You have the option 'Compare Normal only to Reference' enabled. There are no results because you have not designated any folders as Reference."
> ... or maybe that instead of an option, it could be a folder State (along with Normal, Reference, Excluded). But then again, what should be call it?
> 

If you choose to control the new feature through a new folder state, it could be called "Compare only to Reference" and the items can then only be matched to items in Reference folders, and not to other items in the same folder or items in other "Normal" or "Compare only to Reference" folders.

Thanks for your interest and quick reply.

T Koyn

**Comment by hsoft** [comment]
An option would be needed, yes. dupeGuru has always worked the way it does now w.r.t. reference/normal matching. Maybe it doesn't work well for some workflows, but it works well with some and we wouldn't want to pull the rug from under users' feet.

It might be worth it to try to find something more self-explanatory than "Match Normal only to Reference", but then, maybe it's not possible. So I guess that this name is clear enough, if accompanied with a section in the documentation.

@mmoole , could you confirm whether @tkoyn proposition is aligned with yours?

If yes, then all we need is a PR. I'll be glad to review/merge it.

**Comment by tkoyn** [comment]
On Jun 23, 2015, at 11:23 AM, Virgil Dupras <notifications@github.com> wrote:
> @mmoole , could you confirm whether @tkoyn proposition is aligned with yours?
> 
> If yes, then all we need is a PR. I'll be glad to review/merge it.
> 
Just curious what happens if the OP doesn't reply? I hope this can move forward without him if need be, as I need the feature. I still have not had time to set up the build environment, but if I do, I will probably just implement for my private use what I first proposed, as I do not need the user option for my use.

Thanks for your interest in the feature.

**Comment by mmoole** [comment]
well,
as far as I understood, it is really close to what I proposed, I think.

What I am not sure about is what happens to duplicates that are not 'partly' in at least one reference folder (normal duplicates just in the normal folders). They should also be filtered out, as to my original proposition.

In the meantime I was looking around a bit and found easyduplicatefinder.com.
This has a so called 'master select mode' that 'Allows to specify a folder or folders that will be used as search criteria' and works exactly as needed.
Maybe that's a helps as input for naming the preference..

**Comment by tkoyn** [comment]
On Jun 25, 2015, at 4:03 PM, mmoole <notifications@github.com> wrote:

> What I am not sure about is what happens to duplicates that are not 'partly' in at least one reference folder (normal duplicates just in the normal folders). They should also be filtered out, as to my original proposition.
> 

That is exactly what my proposal accomplishes. If a file A1 exists in a Normal folder and a duplicate A2 exists in the same or another Normal folder, A1 will no longer be matched with A2.

(I have not heard of the alternative application you mentioned, so I am not familiar with its approach to the problem of finding duplicates.)

**Comment by tkoyn** [comment]
On Jun 25, 2015, at 4:03 PM, mmoole <notifications@github.com> wrote:

> __edit:
> and this should apply vice versa to only duplicates in reference folders.

Dupe Guru already will never match two files that are both Reference, even if they are duplicate.

**Comment by mmoole** [comment]
great, then lets go and see it in action :+1:

**Comment by mmoole** [comment]
another idea for the preference naming:
Checkbox: Treat Reference files as master list for identifying duplicates

**Comment by tkoyn** [comment]
Agreed. When can this move forward? hsoft, when do you think you can provide the UI change? (I only provided logic that would permanently enable the new feature.)

Thanks

**Comment by hsoft** [comment]
@tkoyn truth is that [I'm not interested in actively developing dupeGuru](http://www.hardcoded.net/archive2014#2014-12-28). I'm really looking to [foster external contributions](https://github.com/hsoft/dupeguru/issues/300), so I'll wait until someone submits a PR.

I'm more than willing to mentor anyone trying to put that PR together, but I will not do it myself.

**Comment by tkoyn** [comment]
I setup to build DupuGuru (as is, without any changes), to get the build process working and I seem to be having an issue building the unaltered program. hsoft, Can you please advise what I might have missed?

Working in OS X, 10.8.5, I did the following

1) Installed Xcode 4.6.3. I believe this is the last one with the OS X 10.7.x SDK

2) Installed Command Line Tools OS X Mountain Lion for XCode September 2013 (the last version released in the the days of Xcode 4.x)

3) Installed Python 3.4.3

4) Installed Setuptools 18.0.1 ad directed at the page https://pypi.python.org/pypi/setuptools
While as root, I executed
curl https://bootstrap.pypa.io/ez_setup.py -o - | python         (appeared successful)

5) Build by running these commands in Terminal
./bootstrap.sh      (appeared successful)
. env/bin/activate && python configure.py && python build.py && python run.py

The error I get is below

Traceback (most recent call last):
  File "build.py", line 401, in <module>
    main()
  File "build.py", line 398, in main
    build_normal(edition, ui, dev, conf)
  File "build.py", line 358, in build_normal
    build_cocoa(edition, dev)
  File "build.py", line 122, in build_cocoa
    build_localizations('cocoa', edition)
  File "build.py", line 209, in build_localizations
    loc.build_cocoa_localizations(app, en_stringsfile=op.join('cocoa', 'base', 'en.lproj', 'Localizable.strings'))
  File "/Users/machorses2/Desktop/dupeguru_build/hscommon/loc.py", line 192, in build_cocoa_localizations
    po2strings(pofile, en_cocoastringsfile, op.join(dest_lproj, 'cocoalib.strings'))
  File "/Users/machorses2/Desktop/dupeguru_build/hscommon/loc.py", line 139, in po2strings
    po = polib.pofile(pofile)
  File "/Users/machorses2/Desktop/dupeguru_build/env/lib/python3.4/site-packages/polib.py", line 138, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "/Users/machorses2/Desktop/dupeguru_build/env/lib/python3.4/site-packages/polib.py", line 86, in _pofile_or_mofile
    instance = parser.parse()
  File "/Users/machorses2/Desktop/dupeguru_build/env/lib/python3.4/site-packages/polib.py", line 1383, in parse
    (self.instance.fpath, self.current_line))
OSError: Syntax error in po file None (line 1)

**Comment by hsoft** [comment]
Oops, sorry about that @tkoyn, it was me who did a sloppy job when I added the Korean and Polish languages recently. If you pull from `master`, things should be fixed now.

**Comment by hsoft** [comment]
Oh, also, the step 4 in your build process is not needed. dupeGuru's bootstrapping process makes sure that setuptools/pip is properly installed in the virtualenv.

**Comment by tkoyn** [comment]
Thanks. I will try again. 

So, is the head of the master branch now the exact same version of the code that created the current publicly available binary of Dupe Guru?

**Comment by hsoft** [comment]
@tkoyn no, not quite. If you want the exact same code, you have to checkout the tag corresponding to the version that you want (all versions are tagged in the git repo).

But for the purpose of this ticket, there has been no commit in `master`, since the latest release, that will affect you, so you might as well use `master`.

**Comment by tkoyn** [comment]
If I start with master, what other changes will I pick up, as compared to the released binary? Are those changes tested both for functionality and for any appropriate regression testing?

**Comment by hsoft** [comment]
Most changes are documentation-or-localization-related. I encourage you to look at the commit log. There's been less than a dozen commits on master since the latest release.

**Comment by tkoyn** [comment]
Thanks, hsoft, for the new commit. I was able to build. I then generated another build adding the lines of code I mention above in this ticket and will test my logic change. As of yet, I have done nothing for the UI to create a user option.

I notice that DupeGuru requires OS X 10.7 to run and that the last version that runs in 10.6 is v 3.8. I am curious what in the current code base exceeds the APIs of Snow Leopard or why you needed to raise the system requirements? I would like my new feature to work in 10.6 (at least in a private build for one of my systems for my own use). It seems I would need to use the 3.8 code base for that purpose. Given that I made a build in 10.8 with the latest code, what would be different about building in and/or for 10.6?

Also, for the current code, what is the earliest and latest versions of OS X, XCode, and Python that may be used for the code as it is now?

Thanks

**Comment by hsoft** [comment]
dupeGuru should normally work on the 10.6 API. I bumped requirements to 10.7 because that's the earliest machine (in a VM) I have on hands. Prior to 10.7, Apple didn't allow running OS X in a VM, so it's a bit harder to maintain a 10.6 build environment.

If your build machine is 10.6, then I *think* it will build out-of-the box, but I can't be certain. Who knows, maybe I've accidentally started using a 10.7 API call.

As for XCode/Python requirements, they're documented in the README.

**Comment by tkoyn** [comment]
I made a refinement in the logic. When I tested the logic change I posted above, I found that if there is more than one duplicate in the non-references folder(s) that they would not be grouped. And furthermore, if there were not duplicates under reference of the file, only one non-reference match would be found. The logic change I have successfully tested is as follows

In scanner.py, get_dupe_groups function....

1) Right after we set is_ref to False for files that do not have the is_ref attribute, add

    # Determine if there are any reference files.
    any_reference_files = any(f.is_ref for f in files)    
2) Right after we remove matches where both files are reference, add the following

    # If there are any reference files we need to exclude matches 
    # where both files are not reference. But to ensure that grouping works
    # correctly, keep match pairs that are both non-reference, if there exists
    # another match with one of the two files being matched to a reference file.
    if any_reference_files:
        matches = [m for m in matches if (not (not m.first.is_ref and not m.second.is_ref)) or
        ( [a for a in matches if m.first.path == a.first.path and a.second.is_ref] or
          [b for b in matches if m.second.path == b.second.path and b.first.is_ref])
        ]

This is my test and test result for this logic.

The file structure, like colored files are duplicates to each other.


The input to DupeGuru



The result

Note. The additional logic I added was needed to get the blue and green file groups to show their multiple duplicates.

**Comment by tkoyn** [comment]
hsoft,

I believe my new logic change will find all the same duplicate sets that it would find before, except that it will never put a non-reference file in the reference position since if will omit any group of duplicates from the results that include no reference file.

I would still be interested in better understanding the grouping process that follows the code I inserted. Could the details of the grouping algorithm be elaborated more in the developer documentation? (I saw you were looking for suggestions on the developer documentation.)

Also, you are right, the built application does still run on 10.6 (at least in brief testing) even though there is no 10.6 SDK involved in the build process.

I am curious, what do you think it would take to run the build process in OS X 10.10 Yosemite (while retaining Snow Leopard runtime compatibility)?

**Comment by hsoft** [comment]
I have yet to analyze your logic, but regarding building Mac apps while targeting an older OS X version than the one it's being built on, I've tried that once (there's a config option to target an older SDK), but the resulting app was unstable (crashed randomly) on older OS X version. I said "screw that" and I built myself a virtual build environment. That works well.

I'm not sure what was the cause of those random crashes, but I'm not really interested in spending time on that issue again.

**Comment by hsoft** [comment]
**About grouping:** For a dupe group to be created, all dupes in the group have to match *with each other*. So if you remove matches where both files come from non-ref folder, you're effectively breaking the group, yes.

If the end result of that new algorithm is that it removes groups where the reference comes from a non-ref folder, how about pruning those groups *after* the grouping phase rather than before? Or even better, why not implement this as a dupe result filter so we let the use remove those dupe groups herself?

**Comment by tkoyn** [comment]
I have added code to implement a UI checkbox. I called it "Require reference" and it defaults off. Clicking it enables my modified logic. At this point I have modified enough of the source files that I am not going to state my code changes here. (Note: Regarding the .po files I left blank strings for all the languages that I do not speak or write as far as translating "Require reference" to other languages go.)

I have a GitHub account and have GitHub and Git installed on my Mac. May I have permission to create a feature branch on the official repo for this project and check in my code? (I am not sure if I technically have or have not access at this point, but I ask in the spirit of working together.)

![screen shot 2015-07-30 at 7 30 52 am](https://cloud.githubusercontent.com/assets/9936123/8983216/f9ae0656-368d-11e5-9c25-0ce2ac96fff7.png)

**Comment by hsoft** [comment]
> May I have permission to create a feature branch on the official repo for this project and check in my code?

Yes, of course. Git's development model is fundamentally different than traditional models such as SVN's. It's a "fork and pull" model. What you do is fork dupeguru's repo and do whatever you want on your private copy. Then, when your work is ready to be merged in the main repo, you make a pull request.

Github has a [documentation page about the process](https://help.github.com/articles/using-pull-requests/) which I would recommend reading. Please let me know if you have further question.

Also, as we can see on the screenshot, you'll need to enlarge the window.

**Comment by hsoft** [comment]
For the .po, no problem. No one is expected to speak all supported languages. This string will simply be marked as "to translate" on transifex and the next time a translator come around, she'll update her language.

**Comment by tkoyn** [comment]
Hi
> What you do is fork dupeguru's repo and do whatever you want on your private copy. Then, when your work is ready to be merged in the main repo, you make a pull request.
> 
What I was proposing to do was create a branch on the main public repo so that my code can be publicly seen and updated by others (including language translators) and then you could merge it to master branch when it is ready to officially become part of the product. Is this what the fork process does, eg create publicly accessible commits of my work in progress?
> Also, as we can see on the screenshot, you'll need to enlarge the window.
> 
I will fix this.

**Comment by hsoft** [comment]
It is not necessary to create a branch in the main repo. Forks are publicly accessible. For example, look at a one of my recent fork of a lib: https://github.com/hsoft/rustty

I created a branch for a feature I wanted to add, `handle-out-of-bounds`. This branch is present *only in my fork*, not in the main repo. But still, it's publicly accessible. Then, when it was ready, I submitted a pull request at https://github.com/cpjreynolds/rustty/pull/2 which was then merged in the main repo.

**Comment by tkoyn** [comment]
I have forked the repo to https://github.com/tkoyn/dupeguru and added a branch feature_tkoyn_require_reference that holds my changes. I believe the changes are working except I don't have all the language translations filled in. I fixed the dialog size.

**Comment by hsoft** [comment]
It's looking good at a glance, thanks for your effort. The next step would be to initiate a pull request so we can proceed with code review.

**Comment by tkoyn** [comment]
I am having an issue with run time performance in my changes that I posted in my fork with a certain situation of a large comparison. I am working on adding certain optimizations for when the program is configured to require reference and to do content scanning, but am having some issues.

I have a specific question - how do I enable logging and where do I see the log file? I want to write details of the program's processing to a log file to examine after execution to help me follow what is happening.

**Comment by hsoft** [comment]
There's a "Debug mode" option in the preference and, on OS X, we log to the Console, so opening the Console will give you access to debug logs.

Log with the `logging` module.

**Comment by MobiusTesseract** [comment]
It's been a while but this was never pulled to the basecode, did you give up on it @tkoyn?

I just introduced myself to dupeGuru today and this feature is exactly what I wanted and what I expected by setting a folder as "Reference". Seeing it did not work like that, what first came in my mind when I tried to put it in words and do a search was **match only against reference**. So I think you were spot on with your suggestions regarding naming this feature in your second comment! On the other hand, I believe "Require reference" will make no sense to someone who is not already thinking about this, until given a proper lengthy explanation.

**Comment by novelero** [comment]
When will "Mass folder state assignment" be included?

**Comment by hsoft** [comment]
@novelero when someone takes the time to implement it? It could even be you!

**Comment by orbittwz** [comment]
Hey! tried using this program as well, Windows 10 user here...
I don't seem to understand if there is an option to instruct the program to compare and match files from **different** folders only.
I'm selecting the root folder, and that root folder has folders in it and the program is suppose to compare between those folders, 
and not match files from the same currently scanned folder.

**Comment by PJDude** [comment]
@orbittwz so You expect to leave duplicates (files with different names) in any folder but find them elsewhere? Strange idea (or I don't understand it). Anyway, you can check the "Cross paths" option in _dude_:
https://github.com/PJDude/dude

**Comment by orbittwz** [comment]
no that's not what I've meant.
the problem lies in the way folders are selected, if I select a root folder and within there are folders, it's not going to work because it's checking for files in the same folder.
if I select folders one by one, I'm guessing it's going to work...
