### ISSUE TITLE
Error when deleting dupes

### ISSUE THREAD

**Issue by JohnReid** [hsoft/dupeguru#324]
I ran dedupeguru ME on a large set of files then selected subsets of them to send to trash. On sending the last set to trash I got this error:
Application Name: dupeGuru Music Edition
Version: 6.8.1

Traceback (most recent call last):
  File "/mnt/Seagate2Tb/home/john/src/dupeguru/qtlib/table.py", line 85, in data
    return self._getData(row, column, role)
  File "/mnt/Seagate2Tb/home/john/src/dupeguru/qt/base/results_model.py", line 35, in _getData
    elif row.is_cell_delta(column.name):
  File "/mnt/Seagate2Tb/home/john/src/dupeguru/core/gui/result_table.py", line 43, in is_cell_delta
    ref_info = self._group.ref.get_display_info(group=self._group, delta=False)
AttributeError: 'NoneType' object has no attribute 'get_display_info'

**Comment by hsoft** [comment]
Duplicate to #272
