### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_display_info'

### ISSUE THREAD

**Issue by ozw1z5rd** [hsoft/dupeguru#330]
```
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\qtlib\table.py", line 85, in data
  File "C:\src\dupeguru\qt\base\results_model.py", line 35, in _getData
  File "C:\src\dupeguru\core\gui\result_table.py", line 43, in is_cell_delta
AttributeError: 'NoneType' object has no attribute 'get_display_info'
```

**Comment by hsoft** [comment]
Duplicate to #272

**Comment by hsoft** [comment]
It's not an uncommon error, but I couldn't reproduce the bug yet, so any extra details about what state the application was in prior to the crash would help.
