### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by djnikosp** [hsoft/dupeguru#337]
```
Application Name: dupeGuru Picture Edition
Version: 2.10.1

Traceback (most recent call last):
  File "/usr/share/dupeguru_pe/qtlib/selectable_list.py", line 26, in data
    return self.model[index.row()]
  File "/usr/share/dupeguru_pe/hscommon/gui/selectable_list.py", line 115, in __getitem__
    return self._items.__getitem__(key)
IndexError: list index out of range
```

**Comment by hsoft** [comment]
Probably related to #309

**Comment by hsoft** [comment]
@djnikosp is your situation similar to the one described by @cecilieaux in #309?

**Comment by djnikosp** [comment]
@hsoft Yes, you are right!
Sorry i posted it before seeing it.

**Comment by hsoft** [comment]
No problem, closing as duplicate.
