### ISSUE TITLE
IndexErrors in Re-Prioritize Duplicates dialog

### ISSUE THREAD

**Issue by gordon-morehouse** [hsoft/dupeguru#353]
**WHAT ACTUALLY HAPPENED**

  1. Open the Re-Prioritize Duplicates dialog from the Actions drop-down menu.
  1. Select "Folder"
  1. Move 2 folders into the right pane using the right-pointed arrow
  1. Attempt to move a folder back into the left pane using the left-pointed arrow
  1. The error report dialog appears several times with identical contents, as below:

```
Application Name: dupeGuru Picture Edition
Version: 2.10.1

Traceback (most recent call last):
  File "/usr/share/dupeguru_pe/qtlib/selectable_list.py", line 26, in data
    return self.model[index.row()]
  File "/usr/share/dupeguru_pe/hscommon/gui/selectable_list.py", line 115, in __getitem__
    return self._items.__getitem__(key)
IndexError: list index out of range
```

**Comment by hsoft** [comment]
Could this be a duplicate to #282?
