### ISSUE TITLE
Loading results issue

### ISSUE THREAD

**Issue by racemus** [hsoft/dupeguru#380]
Can't load saved results. Here is traceback:

```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.0
Mac OS X Version: Version 10.11.6 (Build 15G31)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 205, in selectRows_
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/selectable_list.py", line 61, in select
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/result_table.py", line 99, in _update_selection
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 337, in _select_dupes
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 33, in notify
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 72, in dispatch
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/details_panel.py", line 47, in dupes_selected
AttributeError: 'NoneType' object has no attribute 'refresh'
```

**Comment by hsoft** [comment]
Thanks for your bug report. I'll look into it.

**Comment by sijnak** [comment]
I just got the same error.

for information, I just got an update of dupeguru to 4.0.0 but the results were generated by an older version.

And thanks for the awesome piece of software !

**Comment by dburwitz** [comment]
Same error and callstack, trying to load results from same version

**Comment by sheykandi** [comment]
Same issue here!
Trying to load results recently generated with same version of Dupeguru.

Error traceback:
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.0
Mac OS X Version: Version 10.11.6 (Build 15G31)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 205, in selectRows_
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/selectable_list.py", line 61, in select
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/result_table.py", line 99, in _update_selection
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 337, in _select_dupes
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 33, in notify
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 72, in dispatch
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/details_panel.py", line 47, in dupes_selected
AttributeError: 'NoneType' object has no attribute 'refresh'

Thanks for checking!

**Comment by andymation** [comment]
Same error here:Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.0
Mac OS X Version: Version 10.10.5 (Build 14F1808)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 205, in selectRows_
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/selectable_list.py", line 61, in select
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/result_table.py", line 99, in _update_selection
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 337, in _select_dupes
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 33, in notify
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 72, in dispatch
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/details_panel.py", line 47, in dupes_selected
AttributeError: 'NoneType' object has no attribute 'refresh'

**Comment by sheykandi** [comment]
Confirmed! With v4.0.1 this issue has been fixed. 
Great job, guys! 
Thanks a lot!
