### ISSUE TITLE
line 259, in pulse

### ISSUE THREAD

**Issue by blindasabat** [hsoft/dupeguru#400]
Application Identifier: com.hardcoded-software.dupeguru-pe
Application Version: 2.10.1
Mac OS X Version: Version 10.11.6 (Build 15G1108)

Traceback (most recent call last):
  File "build/dupeGuru PE.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 92, in pulse
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 59, in reraise_if_error
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru PE.app/Contents/Resources/py/core/app.py", line 743, in do
  File "build/dupeGuru PE.app/Contents/Resources/py/core/scanner.py", line 134, in get_dupe_groups
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/scanner.py", line 21, in _getmatches
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/matchblock.py", line 160, in getmatches
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/matchblock.py", line 58, in prepare_pictures
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 152, in purge_outdated
sqlite3.DatabaseError: database disk image is malformed
[Dups.zip](https://github.com/hsoft/dupeguru/files/602264/Dups.zip)

**Comment by hsoft** [comment]
Duplicate to #311
