### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by djwildbill** [hsoft/dupeguru#417]
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\hscommon\gui\progress_window.py", line 92, in pulse
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 59, in reraise_if_error
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\src\dupeguru\core\app.py", line 743, in do
  File "C:\src\dupeguru\core\scanner.py", line 134, in get_dupe_groups
  File "C:\src\dupeguru\core\scanner.py", line 85, in _getmatches
  File "C:\src\dupeguru\core\engine.py", line 275, in getmatches_by_contents
MemoryError

**Comment by hsoft** [comment]
Duplicate to #356

**Comment by ericlindell** [comment]
ERROR MESSAGE BELOW.
This error cleared up when i excluded a directory from the search.
I can provide more info if necessary.



Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.13.3 (Build 17D47)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 776, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 159, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 90, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 257, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 244, in get_file
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/path.py", line 226, in wrapped
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 22, in can_handle
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined

**Comment by arsenetar** [comment]
This second error here seems to be a duplicate of #389
