### ISSUE TITLE
Picture scan error

### ISSUE THREAD

**Issue by Mike-TB** [hsoft/dupeguru#422]
Hi,

I received the following error as I was scanning for duplicates. Previously it worked just fine. I tried reinstalling the app and received the same error.

pplication Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.4 (Build 16E195)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/teacheraccount/Library/Containers/com.apple.BKAgentService/Data/Documents/iBooks/Books/1118588103.ibooks/OPS/assets/images/gallery_fallback-4.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/teacheraccount/Library/Containers/com.apple.BKAgentService/Data/Documents/iBooks/Books/1118588103.ibooks/OPS/assets/images/gallery_fallback-4.png'

**Comment by hsoft** [comment]
Duplicate to #402

**Comment by Mike-TB** [comment]
Thank you. Any resolution?

**Comment by hsoft** [comment]
@Mike-TB as you can see in #402, no. I'm hoping someone having the error would submit a fix.

**Comment by Mike-TB** [comment]
Thanks.  I was hoping ...

**Comment by Mike-TB** [comment]
I've reverted back to PE to see if that works.
