### ISSUE TITLE
I have no idea what's going on

### ISSUE THREAD

**Issue by Shadorexx** [hsoft/dupeguru#426]
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\hscommon\gui\progress_window.py", line 92, in pulse
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 59, in reraise_if_error
  File "C:\src\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\src\dupeguru\core\app.py", line 743, in do
  File "C:\src\dupeguru\core\scanner.py", line 134, in get_dupe_groups
  File "C:\src\dupeguru\core\scanner.py", line 85, in _getmatches
  File "C:\src\dupeguru\core\engine.py", line 275, in getmatches_by_contents
MemoryError

>>What do I do?

**Comment by hsoft** [comment]
Duplicate to #356
