### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Matttribal** [hsoft/dupeguru#467]
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse
  File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close
AttributeError: 'ProgressWindow' object has no attribute '_timer'

**Comment by hsoft** [comment]
Probably a duplicate of #449
