### ISSUE TITLE
DupeGuru 4.0.3 for OSX picture search error

### ISSUE THREAD

**Issue by mummifiedclown** [hsoft/dupeguru#468]
Getting the following error report when trying to do a Picture->Contents scan.  Does not appear to be related to the scan of any particular directory or set of images. Have already tried deleting the app and replacing.
Thx

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.6 (Build 16G1036)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:21042'

**Comment by hsoft** [comment]
Duplicate to #439

**Comment by mummifiedclown** [comment]
The shelvetest version of 4.0.3 appears to work ok - thanks for the quick response.
