### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by moehusni** [hsoft/dupeguru#475]
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse
  File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close
AttributeError: 'ProgressWindow' object has no attribute '_timer'

**Comment by arsenetar** [comment]
Possibly a duplicate of #449.

**Comment by arsenetar** [comment]
Duplicate of #449 and fixed in #460.
