### ISSUE TITLE
Dupeguru fails to build on Arch Linux

### ISSUE THREAD

**Issue by nick-s-b** [hsoft/dupeguru#523]
Hi all,
Could someone help me get dupeguru running under Arch Linux? I get this buld error:

```
Building localizations
Building Qt stuff
pyrcc5 qt/dg.qrc > qt/dg_rc.py
Generating Help
Traceback (most recent call last):
  File "/home/user/.cache/yay/dupeguru/src/hscommon/build.py", line 278, in iter_by_three
    version = next(it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build.py", line 376, in <module>
    main()
  File "build.py", line 373, in main
    build_normal(ui, options.dev)
  File "build.py", line 336, in build_normal
    build_qt(dev)
  File "build.py", line 169, in build_qt
    build_help()
  File "build.py", line 183, in build_help
    sphinxgen.gen(help_basepath, help_destpath, changelog_path, tixurl, confrepl, conftmpl, changelogtmpl)
  File "/home/user/.cache/yay/dupeguru/src/hscommon/sphinxgen.py", line 47, in gen
    changelog = read_changelog_file(changelogpath)
  File "/home/user/.cache/yay/dupeguru/src/hscommon/build.py", line 288, in read_changelog_file
    for version, date_str, description in iter_by_three(iter(splitted)):
RuntimeError: generator raised StopIteration
==> ERROR: A failure occurred in build().
    Aborting...
Error making: dupeguru
````
Thanks!

**Comment by Technifocal** [comment]
[In the AUR package](https://aur.archlinux.org/packages/dupeguru) somebody had a fix:

```
prepare(){
  cd "$srcdir"
  sed -i '277 a\\            try:' src/hscommon/build.py
  sed -i '279s/^/    /' src/hscommon/build.py
  sed -i '280s/^/    /' src/hscommon/build.py
  sed -i '281s/^/    /' src/hscommon/build.py
  sed -i '281a\\            except StopIteration:' src/hscommon/build.py
  sed -i '282a\\                return' src/hscommon/build.py
}
```

I had to delete the `src/` prefix before each directory:

```
prepare(){
  cd "$srcdir"
  sed -i '277 a\\            try:' hscommon/build.py
  sed -i '279s/^/    /' hscommon/build.py
  sed -i '280s/^/    /' hscommon/build.py
  sed -i '281s/^/    /' hscommon/build.py
  sed -i '281a\\            except StopIteration:' hscommon/build.py
  sed -i '282a\\                return' hscommon/build.py
}
```

**Comment by nick-s-b** [comment]
Thank you @Technifocal ! Works!
